### ISSUE TITLE
Mapping function at a specific level

### ISSUE THREAD

**Issue by renkun-ken** [renkun-ken/rlist#101]
Consider the following nested data:

```yaml
a1:
  x1:
    y1: [1, 2, 3]
    y2: [2, 3, 5]
  x2:
    y2: [0, 0, 1]
a2:
  m1:
    y1: 
      y11: [1, 4, 2]
      y12: [2, 5, 1]
    y2: [0, 1, 0]
    y3: [0, 0, 2]
  m2:
    y3: [0, 1, 1]
```

To map at level 3 nodes, using existing rlist functions can be redundant. It may look like

```r
library(rlist)
library(pipeR)
f <- function(x) { NULL }

x %>>% 
  list.map(l1 ~ l1 %>>% 
      list.map(l2 ~ l2 %>>% 
          list.map(l3 ~ f(l3))))
```

Design a function to make it easier to map at a given level.
